services:
  - type: web
    name: youtube-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-db
          property: connectionString
      - key: FLASK_ENV
        value: production
