"""Initial migration

Revision ID: 57be75aa4590
Revises: 
Create Date: 2025-07-09 10:08:57.964312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57be75aa4590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.alter_column('format_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text('("mp4")'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.alter_column('format_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text('("mp4")'))

    # ### end Alembic commands ###
